# Generated by Django 3.2.9 on 2022-11-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
