# Generated by Django 3.2.9 on 2022-11-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221114_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibit', models.CharField(max_length=200)),
                ('gallery', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=200)),
                ('ad', models.ImageField(upload_to='events/')),
                ('artists', models.JSONField()),
            ],
        ),
    ]
